/** Versioned explanatory content. Reuse by explicit module selection, not by
 * relabelling a predecessor page. Equations below are labelled subsets of the
 * implementation, never a second executable model. */
export type ModelModuleDocumentationV1 = Readonly<{
  id: string; title: { ja: string; en: string }; summary: { ja: string; en: string };
  detail: { ja: string; en: string }; equation?: string;
  equationNote?: { ja: string; en: string };
  symbols?: readonly [string, { ja: string; en: string }][];
  additionalEquations?: readonly { expression: string; note: { ja: string; en: string } }[];
  references?: readonly { title: string; url: string; context: { ja: string; en: string } }[];
  owners: readonly string[];
}>;
const t = (ja: string, en: string) => ({ ja, en });
export const MAIN_WIRE_MODEL_MODULES_V1: readonly ModelModuleDocumentationV1[] = [
  { id: "event-calcium-v1", title: t("興奮とCa：収縮のきっかけ", "Activation and calcium"),
    summary: t("心房・心室が興奮すると、細胞内のCa濃度が一過性に上昇します。このCaの変化を入力として、筋原線維の張力を計算します。", "Atrial and ventricular activation events drive calcium transients. Calcium generates pressure through myofilaments and chamber mechanics, not through a prescribed pressure waveform."),
    equation: String.raw`\dot x_r=-x_r/\tau_r,\quad \dot x_d=-x_d/\tau_d,\qquad [Ca]=\mathrm{Ca}_0+g(x_d-x_r)`,
    equationNote: t("時定数が異なる場合の式です。興奮時に二つの状態変数へ同じ量を加えます。速く減る成分と遅く減る成分の差によって、Caが立ち上がり、その後低下します。", "Implemented subset for distinct time constants. Events increment both drives equally; their difference gives a rise and subsequent decay."),
    symbols: [[String.raw`x_r,\;x_d`, t("Ca波形を作る無次元の状態変数", "Dimensionless calcium-drive states")], [String.raw`\tau_r,\;\tau_d`, t("各成分が減衰する時定数（s）", "Decay time constants (s)")], [String.raw`\mathrm{Ca}_0,\;g`, t("興奮が長く途絶えたときのCa濃度と、波形の振幅係数（µM）", "Event-free calcium limit and amplitude coefficient (µM)")]],
    detail: t("baselineは規則的な洞調律です。心房の興奮と、遅れて起こる心室の興奮を扱います。心室では二つの指数関数を組み合わせてCa波形を定め、心房には別の設定を使います。細胞内のCa輸送や活動電位の全過程は解きません。前の拍の成分が残るため、Ca₀と実際の1拍の最低Ca濃度は異なります。", "Regular sinus rhythm includes atrial capture and ventricular conduction. Ventricles use a calibrated biexponential event source; atria retain a separate source. This is not a full action-potential or intracellular calcium-cycling model. Ca₀ is the long event-free limit, not the periodic trough."),
    owners: ["engine/myocardium/calcium/exactEventPrescribedCalciumV1.ts", "engine/myocardium/rhythm/acceptedComposedRhythmTransactionV2.ts"] },
  { id: "land-deactivation-v2", title: t("筋原線維：Caから張力へ", "Myofilaments: calcium to tension"),
    summary: t("アクチンとミオシンが結びつくクロスブリッジの割合と、その歪みから能動張力を計算します。同じCa濃度でも、心筋の長さや短縮速度、過去に受けた負荷によって力が変わります。", "Calcium binding, crossbridge populations, stretch and shortening velocity determine active tension. Force depends on length and loading history even at the same calcium level."),
    equation: String.raw`T_a=\frac{h(\lambda)T_{\mathrm{ref}}}{r_s}\left[S(1+\zeta_s)+W\zeta_w\right]`,
    equationNote: t("Land由来の能動線維応力の出力式（Pa）。W/Sは弱・強結合の割合、ζは歪み、hは長さ依存係数。心腔圧そのものではありません。", "Land-derived active fiber stress output (Pa): W/S are weak/strong populations, ζ their distortions and h a length-dependent factor. This is not cavity pressure."),
    detail: t("Landら（2017）の収縮モデルを基礎に、心室の張力係数・Ca感受性・結合速度を調整しています。さらに、Ca結合が低下したときに強結合の余剰分を非結合状態へ戻す項を加えました。各状態の割合の合計は保ちますが、追加した機構の生理的妥当性には別途検証が必要です。", "Based on Land 2017, but not an unchanged reproduction. Ventricular stress scale, calcium affinity and transition rates are calibrated. An extension returns excess strong-bound population to the unbound pool at low calcium. Population conservation does not transfer the original paper's validation to this extension. Passive and viscoelastic components complete wall stress."),
    symbols: [[String.raw`T_a,\;T_{\mathrm{ref}}`, t("能動線維応力と、その大きさを決める係数（Pa）", "Active fiber stress and its scale (Pa)")], [String.raw`\lambda,\;h(\lambda)`, t("線維の長さ／基準長と、長さ依存の補正係数（無次元）", "Fiber stretch and length-dependent factor (dimensionless)")], [String.raw`W,\;S,\;r_s`, t("弱結合・強結合の割合と、基準の強結合割合（無次元）", "Weak/strong populations and reference strong fraction")], [String.raw`\zeta_w,\;\zeta_s`, t("結合したクロスブリッジの歪み（無次元）。短縮速度と過去の変形に依存", "Dimensionless crossbridge distortions, dependent on shortening and history")]],
    additionalEquations: [{ expression: String.raw`J_{\mathrm{exit}}=k_{\mathrm{max}}\left(\frac{\theta^n}{\theta^n+c^n}\right)^p\max(S-rW,0),\quad \dot S|_{\mathrm{exit}}=-J_{\mathrm{exit}},\quad \dot U|_{\mathrm{exit}}=J_{\mathrm{exit}}`,
      note: t("追加した強結合離脱の式。cはCaが結合したトロポニンの割合、θはその基準値、nとpは感受性を決める指数です。kmaxは最大離脱速度（s⁻¹）、r＝kws/ksuは歪みゼロでの強／弱結合比、Uは非結合割合です。SがrWを超えた分だけを移します。", "Added exit flux: c is calcium-bound troponin fraction, θ its reference, n/p exponents, kmax a rate (s⁻¹), r=kws/ksu the zero-distortion strong/weak ratio, and U the unbound fraction. Only positive excess is transferred.") }],
    owners: ["engine/myocardium/myofilament/land2017/equations.ts", "engine/myocardium/myofilament/land2017/outputs.ts", "engine/myocardium/myofilament/land2017/strongBridgeDeactivationExitV1.ts"] },
  { id: "passive-viscoelastic-v1", title: t("受動特性：伸びにくさと変形の履歴", "Passive mechanics and deformation history"),
    summary: t("拡張期の圧には、心筋が伸ばされたときの抵抗と、時間をかけて緩む粘弾性が関わります。これらを能動張力に加えて、心臓壁に働く応力を求めます。", "Passive stretch resistance and time-dependent viscoelastic relaxation contribute to diastolic pressure alongside active stress."),
    detail: t("心室の受動応力は、伸びに対して増加する弾性エネルギーから求めます。心房には別の受動則を使います。粘弾性は、変形の履歴を一つの変数で持つMaxwell要素で表します。心室の受動則はKlotzの心室全体のEDPVRを参考にした設計であり、個々の心筋の物性を直接測定した値ではありません。", "Ventricular passive stress derives from convex strain energy; atria use a separate law. A one-state Maxwell branch represents viscoelastic history. The ventricular prior references organ-level Klotz EDPVR, not direct tissue measurements."),
    equation: String.raw`e=\ln\lambda_g,\quad \tau_{\mathrm{pass}}=\frac{d\Psi}{de},\quad \tau_{\mathrm{vis}}=E_v(e-\alpha),\quad \dot\alpha=\frac{e-\alpha}{\tau_v}`,
    equationNote: t("受動・粘弾性部分の関係式です。能動部分はLandの応力に線維伸長比と配向・活動割合を掛け、同じ応力基準に変換して加えます。", "Passive and viscous relations. Land active stress is converted using its stretch and orientation/viability fractions before addition in the same stress convention."),
    symbols: [[String.raw`\lambda_g,\;e,\;\alpha`, t("形状から求めた伸長比、その対数歪み、粘性部分の歪み（無次元）", "Geometric stretch, logarithmic strain, and viscous strain")], [String.raw`\Psi,\;\tau_{\mathrm{pass}},\;\tau_{\mathrm{vis}}`, t("弾性エネルギー密度（J/m³）と、受動・粘性のKirchhoff応力（Pa）", "Energy density (J/m³) and passive/viscous Kirchhoff stresses (Pa)")], [String.raw`E_v,\;\tau_v`, t("粘弾性の弾性率（Pa）と材料の緩和時間（s）。LVPから測る弛緩時定数τとは別", "Viscoelastic modulus (Pa) and material time constant (s), distinct from pressure-derived LV τ")]],
    references: [{ title: "Klotz et al. 2006", url: "https://journals.physiology.org/doi/full/10.1152/ajpheart.01240.2005", context: t("心室全体のEDPVRの参照。採用した心筋の受動則そのものの出典ではありません。", "Organ EDPVR context, not the source of the adopted tissue constitutive law.") }, { title: "Moyer et al. 2015", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4497915/", context: t("心房受動材料の出発点。ここでは等二軸変形に縮約して使います。", "Starting point for atrial passive material, reduced here to equibiaxial deformation.") }],
    owners: ["engine/myocardium/mechanics/equilibriumOneFiberPassiveV1.ts", "engine/myocardium/mechanics/moyer2015AtrialEquibiaxialPassiveV1.ts", "engine/myocardium/mechanics/parallelOneStateSlsV1.ts", "engine/myocardium/mechanics/landSlsWallMaterialV1.ts"] },
  { id: "five-wall-energy-triseg-v1", title: t("心房・心室：張力から圧へ", "Chambers: tension to pressure"),
    summary: t("左室自由壁・中隔・右室自由壁を結合し、左右の心室が中隔を介して影響し合います。これに左右心房を加えた五壁構成です。圧は決め打ちの時間波形ではなく、壁応力と形状の釣り合いから求まります。", "LV free wall, septum and RV free wall interact through shared geometry, with two atrial walls completing the five-wall model. Pressure follows stress and geometry, rather than a prescribed time waveform."),
    equation: String.raw`\delta W=\sum_w V_{\mathrm{m},w}\tau_{\mathrm{f},w}\,\delta\ln\lambda_w,\qquad P_{\mathrm{cavity}}=P_{\mathrm{tm}}+P_{\mathrm{ext}}`,
    equationNote: t("壁をわずかに変形させたときの仕事と、内外の圧の関係です。壁の仕事と心腔の圧–体積仕事を対応させて圧を求め、中隔位置と接合円半径についても力の釣り合いを解きます。", "Wall virtual work is matched to cavity pressure–volume work. Septal position and junction radius also satisfy force balance."),
    symbols: [[String.raw`\delta W,\;V_{\mathrm{m},w}`, t("仮想的な微小変形に伴う仕事（J）と、壁wの心筋体積（m³）", "Virtual work (J) and material volume of wall w (m³)")], [String.raw`\tau_{\mathrm{f},w},\;\lambda_w`, t("各壁のKirchhoff線維応力（Pa）と、形状から決まる伸長比。ここでの応力を表すτは、LVPから測る弛緩時定数とは別の量", "Fiber Kirchhoff stress (Pa) and geometric stretch; this stress τ is distinct from the LVP relaxation time")], [String.raw`P_{\mathrm{cavity}},\;P_{\mathrm{tm}},\;P_{\mathrm{ext}}`, t("心腔内圧、壁を内側から広げる経壁圧、壁の外側にかかる圧。同じ単位で加算", "Cavity, transmural, and external pressures, added in the same units")]],
    detail: t("左室自由壁・中隔・右室自由壁を、共通の円で接する三つの球冠として表します。これがTriSegの形状近似です。患者の3D画像を再現するものではなく、局所的な壁応力やねじれは扱いません。PV loopの縦軸は経壁圧、圧波形の縦軸は心腔内圧です。心膜圧や胸腔圧が変わると、両者の差も変わります。", "Ventricles use spherical-cap TriSeg geometry and an energy-conjugate pressure mapping. Pericardial/thoracic external pressure is distinct from transmural pressure. Geometry is not patient-specific 3D imaging and does not resolve local stress or torsion. PV loops use transmural pressure while pressure waveforms use cavity pressure, so they differ when external pressure is present."),
    references: [{ title: "Lumens et al. 2009 · TriSeg", url: "https://link.springer.com/article/10.1007/s10439-009-9774-2", context: t("三つの壁の形状近似の基礎です。心筋の構成則や圧への変換は本モデルの実装に従い、原著モデル全体の再現とは区別します。", "Basis for three-wall geometry; the present constitutive laws and pressure mapping are not a reproduction of the entire original model.") }],
    owners: ["engine/myocardium/mechanics/energyConjugateTriSegV1.ts", "engine/myocardium/mechanics/MainWireFiveWallLandTriSegProviderV1.ts"] },
  { id: "quasisteady-four-valves-v2", title: t("四弁：圧差から流れへ", "Four valves: pressure difference to flow"),
    summary: t("僧帽弁・大動脈弁・三尖弁・肺動脈弁は、共通の開口・圧損失の構造を使います。面積や逆流口の設定は弁ごとに異なります。", "Mitral, aortic, tricuspid and pulmonary valves share an opening and pressure-loss structure, with valve-specific forward and regurgitant areas."),
    equation: String.raw`\Delta P=R Q+B(A)Q|Q|,\qquad B(A)\propto \rho/A^2`,
    equationNote: t("弁を通る流れがある場合の式です。Qと面積Aの単位換算は係数に含めます。完全閉鎖時は、圧差が残っていてもQ＝0となる閉鎖条件を別に適用します。", "Constitutive law on the flowing branch; coefficients include unit conversions. Exact closure supports a pressure difference at Q=0, so this equation alone does not describe every branch."),
    symbols: [[String.raw`\Delta P,\;Q`, t("弁前後の同時圧差（mmHg）と流量（mL/s）。順行を正とする", "Simultaneous upstream-minus-downstream pressure (mmHg) and forward-positive flow (mL/s)")], [String.raw`A,\;\rho`, t("その時点の有効開口面積と血液密度。面積は最大面積と開口割合から求める", "Current effective orifice area and blood density; area depends on maximum area and opening fraction")], [String.raw`R,\;B`, t("線形抵抗（mmHg·s/mL）と二次損失係数（mmHg·s²/mL²）", "Linear resistance (mmHg·s/mL) and quadratic loss coefficient (mmHg·s²/mL²)")]],
    detail: t("各時刻の流量は圧差から代数的に求め、流量そのものの慣性は持たせません。弁尖の開口割合は過去の状態を引き継ぎ、0〜1の範囲で変わります。有効開口面積（EOA）には縮流の影響を含めるため、流出係数Cdを別に掛けません。弁通過後の圧回復は組み込んでいません。この圧差を、Dopplerのジェット速度から求める勾配や、異なる時刻の圧ピーク同士の差と読み替えることはできません。", "Flow is solved algebraically without a separate inertial flow state, while a bounded leaflet-opening memory remains. EOA already accounts for contraction/discharge; no extra Cd is applied. Standard71 has no local pressure-recovery correction. Raw AV/PV node differences are not Doppler maximum-jet or catheter peak-to-peak gradients."),
    owners: ["engine/valves/MainWireQuasiSteadyOrificeValveV2.ts"] },
  { id: "lumped-algebraic-roots-v1", title: t("血管：蓄える・流す", "Vessels: storage and flow"),
    summary: t("血管のコンプライアンスは血液を蓄える性質、抵抗は流れにくさを表します。体循環と肺循環を閉じた回路として結び、各部の体積と圧を同時に求めます。", "Compliance stores blood and resistance opposes flow. Systemic and pulmonary vessels form a closed circuit in which volume and pressure are solved together."),
    equation: String.raw`\frac{dV_i}{dt}=\sum Q_{\mathrm{in},i}-\sum Q_{\mathrm{out},i},\qquad C_i(P_{\mathrm{tm}})=\frac{dV_i}{dP_{\mathrm{tm},i}}`,
    equationNote: t("体積保存とコンプライアンスの定義。静脈を含む圧–体積関係は必ずしも一定Cの直線ではありません。", "Volume conservation and differential compliance. Pressure–volume relations, including venous vessels, need not be linear with constant C."),
    symbols: [[String.raw`V_i,\;Q_{\mathrm{in}},\;Q_{\mathrm{out}}`, t("区画iの血液量（mL）と、流入・流出量（mL/s）", "Compartment volume (mL) and inflow/outflow (mL/s)")], [String.raw`C_i,\;P_{\mathrm{tm},i}`, t("圧に応じたコンプライアンス（mL/mmHg）と、血管の経壁圧（mmHg）", "Pressure-dependent compliance (mL/mmHg) and transmural vascular pressure (mmHg)")]],
    detail: t("大動脈と肺動脈の近位部では、流体の慣性係数Lを0としています。AoPとPAPには、それぞれの血管区画の圧を表示します。特性インピーダンスと流量の積（ZcQ）を表示時に足す処理はありません。SAは下流の体動脈をまとめた区画です。圧波の伝播や反射を解かないため、カフや特定の動脈ライン位置の波形とは区別します。", "Aortic and pulmonary roots use algebraic flow without local L in Standard71. AoP and PAP are the Ao and PA node pressures, without a displayed ZcQ addition; SA is a downstream systemic-arterial compartment. Travelling/reflected waves, propagation delay and particular cuff/arterial-line sites are not simulated. Venous tone and TBV are not interchangeable controls: they affect filling and blood distribution."),
    owners: ["engine/core/circulationGraphKernelV1.ts", "engine/core/nonCoronaryCirculationBackwardEulerV1.ts"] },
  { id: "coronary-coupling-v3", title: t("冠循環・外圧：心臓と循環の結合", "Coronary and external-pressure coupling"),
    summary: t("冠動脈への流入と静脈への還流も全体の体積収支に含みます。心筋収縮による血管の圧迫が冠血流に影響し、心膜・胸腔圧は心腔や血管を外側から負荷します。", "Coronary inflow and venous return contribute to global volume balance. Myocardial compression modulates coronary flow, while pericardial and thoracic pressures load cavities and vessels externally."),
    detail: t("冠循環は、左前下行枝・回旋枝・右冠動脈の領域を、それぞれ心外膜側と心内膜側に分けます。血管の抵抗と容量に加え、心筋内圧による圧迫・虚脱と自己調節を扱います。一部の係数には、正常成人を想定した暫定値を使っています。baselineでは補助循環・弁逆流・呼吸性変動を加えていません。", "Coronary territories and layers include resistance/storage, intramyocardial pressure, collapse and autoregulation, some with provisional adult priors. Baseline has no mechanical support, valve regurgitation or respiratory oscillation. Fixed-control preload testing holds HR and tone fixed; it is not a bedside fluid challenge with autonomic and whole-body responses."),
    owners: ["engine/coronary/mainWireMechanicsCouplingV1.ts", "engine/coronary/backwardEulerCoronaryNetworkV2.ts"] },
  { id: "oxygen-balance-v1", title: t("酸素輸送：血流から供給と消費を計算", "Oxygen supply and consumption"),
    summary: t("1拍平均の血流と、Hb・吸入酸素濃度・酸素消費量の設定から、全身の酸素需給を計算します。心筋の収縮モデルとは別の計算です。", "Beat-mean flow, hemoglobin, inspired oxygen and prescribed consumption determine systemic oxygen balance separately from myocardial contraction."),
    detail: t("肺胞気式、酸素解離曲線、シャント血の混合を使って動脈血酸素含量を求めます。Fickの関係から必要な混合静脈血酸素含量を逆算し、負の含量を必要とする条件は計算上成立しないと判定します。局所組織の酸素拡散や代謝適応の全過程は再現しません。", "Alveolar gas, oxygen dissociation and shunt mixing determine arterial content. Fick balance gives required mixed-venous content; negative required content is infeasible. Local diffusion and full metabolic adaptation are not resolved."),
    equation: String.raw`\dot D_{\mathrm{O_2}}=10\,\mathrm{CO}\,C_{\mathrm{aO}_2},\qquad \dot V_{\mathrm{O_2}}=10\,\mathrm{CO}(C_{\mathrm{aO}_2}-C_{\mathrm{vO}_2})`,
    symbols: [[String.raw`\mathrm{\mathrm{CO}}`, t("1拍平均の血流量（L/min）", "Beat-mean systemic flow (L/min)")], [String.raw`C_{\mathrm{aO}_2},\;C_{\mathrm{vO}_2}`, t("動脈血と混合静脈血の酸素含量（mL O₂/dL）", "Arterial and mixed-venous oxygen content (mL O₂/dL)")], [String.raw`\dot D_{\mathrm{O}_2},\;\dot V_{\mathrm{O}_2}`, t("酸素供給量と設定した酸素消費量（mL O₂/min）。係数10はLからdLへの換算", "Oxygen delivery and prescribed consumption (mL O₂/min); 10 converts L to dL")]],
    owners: ["engine/physiology/oxygenTransportV1.ts"] },
  { id: "derived-pv-analysis-v3", title: t("解析：負荷を変えて心臓の応答を調べる", "Analysis: relationships beyond one loop"),
    summary: t("1拍のPV loopはシミュレーションが作る軌道です。ESPVR・EDPVR・Starling/Guyton曲線やPVA/PEは、別の負荷条件を計算する解析から得ます。", "A PV loop is the simulated beat trajectory. ESPVR, EDPVR, Starling/Guyton curves and PVA/PE are derived through separate loading protocols."),
    detail: t("解析用に状態を複製するため、操作中のシミュレーションは変わりません。収縮末期圧–容積関係（ESPVR）は低容量側からbaselineまでの複数条件で求めます。拡張末期圧–容積関係（EDPVR）とStarling曲線には高容量側も含めます。推定値は負荷範囲や各条件の定常化に依存し、ESPVRが直線になるとは限りません。曲線や面積の推定が成立しない場合は未評価と表示します。", "Analyses branch without mutating the live simulation. ESPVR uses the reduced-preload limb through baseline; EDPVR and Starling retain high-volume conditions too. Estimates depend on the finite loading range, settlement and event definitions; linearity and load independence are not guaranteed. Unavailable analysis stays unassessed, not an exact-output placeholder."),
    owners: ["analysis/methods/mainWire/MainWirePressureVolumeProtocolsV3.ts"] },
];

export const STANDARD71_MODULE_IDS_V1 = Object.freeze([
  "event-calcium-v1", "land-deactivation-v2", "passive-viscoelastic-v1", "five-wall-energy-triseg-v1",
  "quasisteady-four-valves-v2", "lumped-algebraic-roots-v1", "coronary-coupling-v3", "oxygen-balance-v1", "derived-pv-analysis-v3",
]);
