/** Mathematical descriptions for the selected construction, not a second solver.
 * Symbols are local to a module; numerical coefficients come from its frozen projection. */
const t = (ja: string, en: string) => ({ ja, en });
export type EquationSpecificationBlockV1 = Readonly<{
  id: string; title: ReturnType<typeof t>; paragraphs: readonly ReturnType<typeof t>[];
  equations: readonly string[];
}>;
export const MAIN_WIRE_EQUATION_SPECIFICATION_V1: Readonly<Record<string, readonly EquationSpecificationBlockV1[]>> = {
  "event-calcium-v1": [{
    id: "calcium-events", title: t("興奮時刻・状態の更新", "Activation times and state updates"),
    paragraphs: [t("時間の単位はsです。規則的洞調律では、心房興奮の間隔T＝60/HR、心室興奮はその120 ms後（房室伝導80 ms＋遠位伝導40 ms）です。各心房・心室のCaへの入力は、対応する興奮の12 ms後に加えます。各壁は独立した二つのCa状態を持ちます。", "Time is in seconds. In regular sinus rhythm T=60/HR; ventricular activation follows atrial activation by 120 ms (80 ms AV + 40 ms distal conduction). Calcium deposits occur another 12 ms after the corresponding activation. Each wall has two calcium states."),
      t("qは興奮ごとの入力強度です。baselineでは両心房・三つの心室壁ともq＝1です。イベント間は指数関数で厳密に減衰し、イベント直後に両状態へqを加えます。下式の周期解は規則的なq＝1の場合で、心腔容積やLand状態の初期値を定めるものではありません。", "q is deposit strength, equal to 1 for all five walls at baseline. States decay analytically between events and both receive q at an event. The periodic formula below is for regular unit deposits; it does not initialize chamber volumes or Land states.")],
    equations: [String.raw`t_{A,k}=t_{A,0}+kT,\quad t_{V,k}=t_{A,k}+0.120,\quad t_{Ca,w,k}=t_{A\text{ or }V,k}+0.012`,
      String.raw`x_j(t+\Delta t)=x_j(t)e^{-\Delta t/\tau_j},\quad x_j(t_k^+)=x_j(t_k^-)+q_k\quad(j=r,d)`,
      String.raw`x_j(t_k^+)=\frac{1}{1-e^{-T/\tau_j}}\quad\text{(periodic, }q_k=1\text{)}`],
  }, {
    id: "interval-strength", title: t("心拍間隔とCa入力強度", "Interval-dependent calcium strength"),
    paragraphs: [t("心室には拍間隔依存の離散的な負荷状態Lを持たせます。Iは直前の心室興奮からの間隔、aは回復割合、qは次のCa入力強度です。LはSR負荷を規格化した量で、実測のSR内Ca濃度ではありません。係数と規則的洞調律での基準状態は下の表に示します。基準心拍数に対応するL・aとq＝1が固定点を作ります。", "Ventricles carry a discrete interval-dependent normalized load L, not measured SR calcium concentration. I is the preceding ventricular interval, a recovery and q the next calcium deposit. Coefficients and reference states are tabulated below. L and a at the reference heart rate form a fixed point with q=1."), t("ここで記載する起動条件は規則的洞調律・補助循環なしです。異所性刺激・ペーシング・補助循環装置を有効にした場合の全モードは、このbaselineの方程式系には含めません。", "The construction specified here is regular sinus rhythm without mechanical support. Optional ectopy, pacing and support-device modes are not included in this baseline equation system.")],
    equations: [String.raw`a_k=1-e^{-I_k/\tau_{\mathrm{rec}}},\quad q_k=a_k\beta L_k,\qquad L_{k+1}=L_k-(1-r)q_k+\gamma(1-ha_k)`],
  }],
  "land-deactivation-v2": [{
    id: "land-state-equations", title: t("六つの状態と保存条件", "Six states and conservation"),
    paragraphs: [t("各壁でc＝Ca結合トロポニンの割合、b＝結合が阻害された割合、W＝弱結合、S＝強結合、ζw・ζs＝架橋の歪みを持ちます。結合可能な非結合割合Uは独立状態ではなく、U＝1−b−W−Sです。0＜c≤1、b・U・W・S≥0を満たす解を使います。bは血管・弁の二次抵抗係数とは別の記号です。", "Each wall has c (Ca-bound troponin), b (blocked), W/S (weak/strong binding) and distortions ζw/ζs. U=1−b−W−S is dependent. Valid states require 0<c≤1 and b,U,W,S≥0. b is unrelated to a hydraulic quadratic coefficient."),
      t("Caは自由Ca濃度（µM）、λはLandに入力する伸長比です。gwu・gsuは歪みに伴う離脱速度（s⁻¹）です。Jexitは上で示した追加離脱項で、心室壁に適用します。心房ではJexit＝0です。離脱した割合はUへ戻ります。", "Ca is free calcium (µM); λ is the Land stretch. gwu/gsu are distortion-dependent detachment rates (s⁻¹). The added exit flux above applies to ventricular walls; Jexit=0 in atria. Detached population returns to U.")],
    equations: [String.raw`\begin{aligned}\dot c&=k_{\mathrm{TRPN}}\{(\mathrm{Ca}/\mathrm{Ca}_{50})^{n_{\mathrm{TRPN}}}(1-c)-c\},\\\dot b&=k_b\min(c^{-n_{\mathrm{Tm}}/2},100)U-k_u c^{n_{\mathrm{Tm}}/2}b,\\\dot W&=k_{\mathrm{uw}}U-(k_{\mathrm{wu}}+k_{\mathrm{ws}}+g_{\mathrm{wu}})W,\\\dot S&=k_{\mathrm{ws}}W-(k_{\mathrm{su}}+g_{\mathrm{su}})S-J_{\mathrm{exit}},\\\dot\zeta_w&=A_w\dot\lambda-c_w\zeta_w,\qquad\dot\zeta_s=A_s\dot\lambda-c_s\zeta_s.\end{aligned}`,
      String.raw`\begin{aligned}\lambda_c&=\min(\lambda,1.2),\\\mathrm{Ca}_{50}&=\mathrm{Ca}_{50,\mathrm{ref}}+\beta_1(\lambda_c-1),\\h(\lambda)&=\max\{0,1+\beta_0[\lambda_c+\min(\lambda_c,0.87)-1.87]\},\\g_{\mathrm{wu}}&=\gamma_w|\zeta_w|,\quad g_{\mathrm{su}}=\gamma_s\max(-\zeta_s-1,\zeta_s,0).\end{aligned}`],
  }, {
    id: "land-derived-rates", title: t("派生係数と心臓壁への結合", "Derived rates and wall coupling"),
    paragraphs: [t("表に示す独立係数から、以下の係数を計算します。rₛ・r𝓌は基準結合割合、θ＝TRPN50です。k・cの単位はs⁻¹、Aは無次元です。Ca50が正でない場合は有効な材料条件ではありません。長さ依存をλ＝1.2で飽和させる処理と、トロポニン項の上限100も採用した式の一部です。", "The following rates derive from the independent parameters below. rₛ/r𝓌 are reference fractions, θ=TRPN50. k/c rates are in s⁻¹ and A is dimensionless. Ca50 must remain positive. The λ=1.2 saturation and factor limit 100 are part of the adopted law."),
      t("形状の対数歪みをeとするとλ＝s₀ exp(e)。s₀は筋長基準の倍率で、baselineは全壁で1です。短縮速度には(λn+1−λn)/Δtを使います。Landの出力Tₐをλ・線維配向割合fo・活動割合faで変換し、Kirchhoff応力として受動・粘弾性応力に加えます。fo＝fa＝1です。心室の収縮力倍率はTrefだけに、受動倍率は受動応力と粘弾性弾性率に掛かります。", "With geometric log strain e, λ=s₀ exp(e), where s₀=1 for all baseline walls. The discrete velocity is (λn+1−λn)/Δt. Land Tₐ is multiplied by λ, orientation fo and active fraction fa to obtain Kirchhoff stress. fo=fa=1. Active controls scale Tref; passive controls scale passive stress and viscous modulus.")],
    equations: [String.raw`\begin{aligned}k_b&=\frac{k_u\theta^{n_{\mathrm{Tm}}}}{(1-r_s)(1-r_w)},\quad k_{\mathrm{wu}}=k_{\mathrm{uw}}(1/r_w-1)-k_{\mathrm{ws}},\\k_{\mathrm{su}}&=k_{\mathrm{ws}}r_w(1/r_s-1),\quad A_w=A_s=\frac{A_{\mathrm{eff}}r_s}{(1-r_s)r_w+r_s},\\c_w&=\frac{\phi k_{\mathrm{uw}}(1-r_w)}{r_w},\quad c_s=\frac{\phi k_{\mathrm{ws}}(1-r_s)r_w}{r_s},\\\tau_f&=\lambda f_o f_aT_a+\tau_{\mathrm{pass}}+\tau_{\mathrm{vis}}.\end{aligned}`],
  }],
  "passive-viscoelastic-v1": [{
    id: "ventricular-passive-law", title: t("心室の弾性エネルギー", "Ventricular elastic energy"),
    paragraphs: [t("e＝ln λg、p＝Hδ(e)、q＝Hδ(−e)とします。K0は原点付近の弾性率、Kt・aは伸張時の指数的な硬化、Kcは圧縮側の追加弾性率です。Hδは正の歪みだけを滑らかに取り出す関数で、u＝z/δです。心室三壁には同じ式を使い、エネルギーとその微分に各壁の受動倍率sₚ,ｗを掛けます。倍率はbaselineの設定表に示します。", "Let e=ln λg, p=Hδ(e), q=Hδ(−e). K0 is central stiffness; Kt/a govern tensile stiffening; Kc adds compression stiffness. Hδ is a smooth positive part with u=z/δ. The three ventricular walls share this law; energy and derivatives are multiplied by each wall's passive scale sₚ,ｗ, listed in the baseline settings.")],
    equations: [String.raw`H_\delta(z)=\begin{cases}0&z\le0\\\delta(u^3-\tfrac12u^4)&0<z<\delta\\z-\delta/2&z\ge\delta\end{cases}`, String.raw`\Psi(e)=\tfrac12K_0e^2+\frac{K_t}{a^2}(e^{ap}-1-ap)+\tfrac12K_cq^2,\qquad \tau_{\mathrm{pass}}=s_{p,w}\,\frac{d\Psi}{de}`],
  }, {
    id: "atrial-passive-law", title: t("心房の受動則と粘弾性", "Atrial passive law and viscoelasticity"),
    paragraphs: [t("心房は等二軸変形に縮約した別の材料則を使います。下式のsₚ,ｗは各壁の受動倍率です。λg＝exp(e)、C1・C2・C3はPa、C4は無次元です。線維項は伸張側のみ働きます。対応するエネルギーはΨ(e)＝∫₀ᵉτpass(s)dsで定まります。支持する歪み範囲は−0.5≤e≤0.5です。左房由来の材料を右房にも適用する点は外挿です。", "Atria use a separate equibiaxial reduction; sₚ,ｗ below is each wall's passive multiplier. λg=exp(e); C1/C2/C3 are Pa, C4 dimensionless. The fiber term is tension-only. Energy is Ψ(e)=∫₀ᵉτpass(s)ds. Supported strain is −0.5≤e≤0.5; applying the LA-derived material to RA is an extrapolation."),
      t("全壁の粘弾性は1状態のMaxwell枝です。αは粘性歪み、Evは弾性率、τvは緩和時間です。下式は採用している後退Euler更新で、各力学ステップにつき1回適用します。Evの表は受動倍率を適用済みです。", "Each wall has a one-state Maxwell branch: α is viscous strain, Ev modulus, τv relaxation time. The implemented backward-Euler update below is applied once per mechanics step. Listed Ev already includes the passive scale.")],
    equations: [String.raw`\tau_{\mathrm{pass}}=s_{p,w}\left[4C_1(\lambda_g^2-\lambda_g^{-4})+4C_2(\lambda_g^4-\lambda_g^{-2})+\begin{cases}C_3(e^{C_4(\lambda_g-1)}-1)&e>0\\0&e\le0\end{cases}\right]`, String.raw`\alpha_{n+1}=\frac{\alpha_n+(\Delta t/\tau_v)e_{n+1}}{1+\Delta t/\tau_v},\qquad \tau_{vis,n+1}=E_v(e_{n+1}-\alpha_{n+1})`],
  }],
  "five-wall-energy-triseg-v1": [{
    id: "triseg-geometry", title: t("三つの球冠と心筋長", "Three spherical caps and fiber length"),
    paragraphs: [t("以下の力学式はm・m²・m³・PaのSI単位で書きます。VL・VRは心腔血液量、Mwは各壁の心筋体積、vSは中隔の符号付き球冠体積、y＞0は三壁が接する円の半径です。心筋体積MはTBVには含めません。球冠高さhは右室方向を正とし、左室自由壁では通常負になります。", "Mechanics uses SI units: m, m², m³, Pa. VL/VR are cavity blood volumes, Mw wall material volumes, vS the signed septal cap volume, y>0 the junction-circle radius. Wall material is not part of TBV. Cap height h is positive toward RV, usually negative for LV free wall."),
      t("各壁wについて球冠体積vwからhを求め、面積Aw・曲率κw・厚さ補正zwを計算します。Aref,wは基準中壁面積です。ここでのzwはLandの架橋歪みζとは別物です。形状から得たewを材料則へ入力します。", "For each wall solve h from cap volume, then area Aw, curvature κw and thickness correction zw. Aref,w is reference midwall area. zw is unrelated to Land crossbridge distortion ζ. Geometric ew enters the material law.")],
    equations: [String.raw`v_L=-V_L-\tfrac12(M_L+M_S)+v_S,\qquad v_R=V_R+\tfrac12(M_R+M_S)+v_S`,
      String.raw`v_w=\frac{\pi h_w(h_w^2+3y^2)}6,\quad A_w=\pi(h_w^2+y^2),\quad\kappa_w=\frac{2h_w}{h_w^2+y^2}`, String.raw`z_w=\frac{3\kappa_wM_w}{2A_w},\qquad e_w=\frac12\ln\frac{A_w}{A_{\mathrm{ref},w}}-\frac{z_w^2}{12}-0.019z_w^4`],
  }, {
    id: "triseg-force-balance", title: t("内部の釣り合いと圧の決定", "Internal balance and cavity pressures"),
    paragraphs: [t("Fは球冠体積方向、Gは接合円半径方向の一般化力です。各壁の応力は材料状態と候補形状から求め、その時点の応力を掛けて歪みの幾何学微分を計算します。これを『能動応力がポテンシャルから生じる』と仮定して微分するわけではありません。", "F/G are generalized forces for cap volume and junction radius. Multiply each current material stress by geometric strain derivatives; do not differentiate active stress as though it were a conservative potential."),
      t("心腔容積を与え、三壁の力が釣り合うvS・yを連立して求めます。その解からLV・RV経壁圧が定まります。両心房には球状の一線維近似を使い、Vrefは表の基準心腔血液量です。圧に任意の時間波形や追加の壁別圧倍率を掛けません。", "For supplied cavity volumes solve vS/y simultaneously from force balance, then obtain LV/RV transmural pressures. Atria use a spherical one-fiber reduction with reference cavity volume Vref. No prescribed pressure waveform or wall-specific pressure gain is added.")],
    equations: [String.raw`F_w=M_w\tau_{\mathrm{f},w}\left.\frac{\partial e_w}{\partial v_w}\right|_y,\qquad G_w=M_w\tau_{\mathrm{f},w}\left.\frac{\partial e_w}{\partial y}\right|_{v_w}`, String.raw`F_L+F_S+F_R=0,\quad G_L+G_S+G_R=0,\qquad P_{\mathrm{tm},L}=-F_L,\quad P_{\mathrm{tm},R}=F_R`, String.raw`e_A=\frac13\ln\frac{V_A+M_A/2}{V_{\mathrm{ref},A}+M_A/2},\qquad P_{\mathrm{tm},A}=\frac{M_A\tau_{\mathrm{f},A}}{3(V_A+M_A/2)}`],
  }, {
    id: "pericardial-law", title: t("胸腔圧・心膜圧の加算", "Thoracic and pericardial pressure"),
    paragraphs: [t("心膜内を占める容積VHは、四心腔の血液量＋五壁の心筋体積＋処方した心嚢液量です。冠血液量をここへもう一度加える処理はありません。四心腔に同じ心膜外圧を加えます。V0は基準容量、P*は圧係数、kは硬化係数です。", "Occupied heart volume VH sums four cavity blood volumes, five wall volumes and prescribed pericardial fluid. Coronary blood is not added again to this occupancy formula. All cavities share the same external pressure. V0 is reference capacity, P* pressure scale and k stiffness."),
      t("Hは心膜が張り始める領域を滑らかにした関数です。δ＝0.001、u＝(x＋δ)/(2δ)とします。H′はxでの微分です。baselineでは圧オフセット0、心嚢液0 mL、胸腔・肺胞の呼吸振幅0です。心膜の張りがなければ、心腔内圧と経壁圧は一致します。", "H smooths engagement, δ=0.001 and u=(x+δ)/(2δ). H′ differentiates with respect to x. Baseline pressure offset/fluid/respiratory amplitudes are zero. With no engagement and zero thoracic pressure, cavity and transmural pressures coincide.")],
    equations: [String.raw`V_H=\sum_{c=LA,LV,RA,RV}V_c+\sum_w M_w+V_{\mathrm{fluid}},\quad x=(V_H-V_0)/V_0`, String.raw`H(x)=\begin{cases}0&x\le-\delta\\\delta(2u^3-u^4)&|x|<\delta\\x&x\ge\delta\end{cases}`, String.raw`P_{peri}=P_{\mathrm{offset}}+P_*[e^{kH(x)}-1]H'(x),\qquad P_c=P_{\mathrm{tm},c}+P_{\mathrm{th}}+P_{peri}`],
  }],
  "quasisteady-four-valves-v2": [{
    id: "valve-opening", title: t("開口状態の時間発展", "Opening-state dynamics"),
    paragraphs: [t("ξは開口割合（0〜1）、ΔPは上流圧−下流圧です。dは不感帯、pₒは圧オフセット（baselineは四弁とも0 mmHg）、kₒは開口感度です。Fεは正の開口駆動を滑らかにした関数で、ε＝0.1 mmHgです。ξ∞が直前のξより大きければ開口時定数、それ以外は閉鎖時定数を使います。", "ξ is opening fraction (0–1), ΔP upstream minus downstream pressure, d deadband, pₒ offset (0 mmHg in all baseline valves) and kₒ opening sensitivity. Fε smooths positive opening drive with ε=0.1 mmHg. Use the opening time constant when target exceeds previous ξ, otherwise the closing constant.")],
    equations: [String.raw`F_\epsilon(z)=\begin{cases}0&z\le0\\z^2/(2\epsilon)&0<z<\epsilon\\z-\epsilon/2&z\ge\epsilon\end{cases},\quad \xi_\infty=1-e^{-k_oF_\epsilon(\Delta P-d-p_o)}`, String.raw`\dot\xi=\frac{\xi_\infty-\xi}{\tau_\xi},\qquad \xi_{n+1}=\frac{\xi_n+(\Delta t/\tau_\xi)\xi_\infty(\Delta P_{n+1})}{1+\Delta t/\tau_\xi}`],
  }, {
    id: "valve-flow", title: t("面積・方向・完全閉鎖", "Area, direction and exact closure"),
    paragraphs: [t("Amaxは最大順行EOA、Arは閉鎖時の逆流EOAです。順行では残存開口Arにξで開く部分を加え、逆行ではξによらずArだけを使います。従ってArを増やすと、逆行だけでなく閉鎖近くの順行流も変わります。baselineは全弁Ar＝0です。", "Amax is maximal forward EOA; Ar closed regurgitant EOA. Forward area includes the residual gap plus the opening-dependent part; reverse area is Ar independent of ξ. Changing Ar also affects near-closure forward flow. Baseline Ar=0 in all valves."),
      t("QはmL/s、Aはcm²、圧はmmHg、ρ＝1060 kg/m³、cP＝133.322387415 Pa/mmHgです。面積が0ならQ＝0とし、残る圧差を閉鎖支持反力として扱います。小さな面積の下限や流量の平滑化は置きません。Rは面積に応じて再スケールしません。", "Q is mL/s, A cm², pressure mmHg, ρ=1060 kg/m³, cP=133.322387415 Pa/mmHg. Zero area gives exactly Q=0 with supported pressure difference. No area floor or flow smoothing is introduced. R is not rescaled with area.")],
    equations: [String.raw`A=\begin{cases}A_r+\xi(A_{\mathrm{max}}-A_r)&\Delta P\ge0\\A_r&\Delta P<0\end{cases},\quad B(A)=\frac{\rho}{2c_P}\left(\frac{10^{-6}}{10^{-4}A}\right)^2`, String.raw`Q=\begin{cases}0&A=0\text{ or }\Delta P=0\\\operatorname{sgn}(\Delta P)\frac{2|\Delta P|}{R+\sqrt{R^2+4B(A)|\Delta P|}}&\text{otherwise}\end{cases}`],
  }],
  "lumped-algebraic-roots-v1": [{
    id: "vascular-pv", title: t("血管区画の圧–容量関係", "Compartment pressure–volume laws"),
    paragraphs: [t("圧はmmHg、容積はmL、流量はmL/sです。Pは内圧、p＝P−Pextは経壁圧です。Vuはp＝0での容量で、V−Vuをstressed volumeと呼びます。動脈のVsは表では硬さ・コンプライアンス倍率を適用した値です。Ao・SA・ArtはVs,元×0.65/1.42、PA・PArtはVs,元/1.42です。", "Pressure is mmHg, volume mL and flow mL/s. p=P−Pext is transmural pressure. Vu is volume at p=0; V−Vu is stressed volume. Listed Vs includes stiffness/compliance scaling: original Vs×0.65/1.42 for Ao/SA/Art, original Vs/1.42 for PA/PArt."),
      t("静脈型区画は、虚脱時Cc・開通時Co・高圧伸展時Cdを滑らかに接続します。S(z)＝ln(1＋exp z)、σ(z)＝1/(1＋exp(−z))、ΔS(p;a,d)＝S((p−a)/d)−S(−a/d)とします。静脈トーンuはVu＝Vu,元−G uとして作用し、baselineのu＝0.15を適用したVuを表に示します。", "Venous-type compartments join collapsed Cc, open Co and distended Cd smoothly. S(z)=ln(1+exp z), σ(z)=1/(1+exp(−z)); ΔS(p;a,d)=S((p−a)/d)−S(−a/d). Tone u changes Vu=Vu,original−G u. The table includes baseline u=0.15."),
      t("静脈の逆計算は−20〜45 mmHgに制限し、範囲外では端の圧を返します。動脈は(V−Vu)/Vsの下限をln(0.05)とします。これは正常範囲ではなく計算上の境界で、境界に達した結果を生理的な予測として外挿できません。コンプライアンス評価には下限10⁻⁴ mL/mmHgがありますが、V(p)自体を別の曲線に置き換える処理ではありません。", "The venous inverse saturates at −20/45 mmHg; arterial strain is bounded below by ln(0.05). These are numerical boundaries, not normal ranges; saturated results must not be extrapolated physiologically. Compliance readback is floored at 10⁻⁴ mL/mmHg without replacing V(p).")],
    equations: [String.raw`p=P_0\left(e^{\max[(V-V_u)/V_s,\ln0.05]}-1\right)\quad\text{(arterial)},\qquad p=(V-V_u)/C\quad\text{(linear)}`, String.raw`V(p)=V_u+C_cp+(C_o-C_c)d_o\Delta S(p;p_o,d_o)-(C_o-C_d)d_s\Delta S(p;p_s,d_s)`, String.raw`\frac{dV}{dp}=C_c+(C_o-C_c)\sigma\left(\frac{p-p_o}{d_o}\right)-(C_o-C_d)\sigma\left(\frac{p-p_s}{d_s}\right)`],
  }, {
    id: "vascular-links", title: t("接続部の流量・虚脱・外圧", "Link flow, collapse and external pressure"),
    paragraphs: [t("非弁接続はΔP＝RQ＋BQ|Q|を解きます。現行baselineの非弁接続はB＝0、慣性L＝0なので、通常はQ＝(Pup−Pdown)/Rです。体・肺抵抗倍率は表に示した対象の接続だけに掛かり、全静脈抵抗を一括で変えるものではありません。", "Non-valve links solve ΔP=RQ+BQ|Q|. Current baseline links have B=0 and L=0, normally Q=(Pup−Pdown)/R. Systemic/pulmonary multipliers apply only to the listed groups, not all venous resistances."),
      t("大静脈→右房と肺毛細管→肺細静脈では、外圧により流出が制限されるwaterfallと、虚脱に伴う抵抗増加を使います。M±は平滑な最大・最小、ε＝0.25 mmHg。χmin＝0.08、幅w＝1 mmHg、臨界圧pc＝0です。χは補正前の両端圧から計算し、下流有効圧を二重に代入しません。", "VC→RA and PCap→PVen use a waterfall and collapse-dependent resistance. M± are smooth max/min with ε=0.25 mmHg; χmin=0.08, w=1 mmHg, pc=0. χ uses raw endpoint pressures, not the already modified downstream pressure."),
      t("胸腔圧Pthと肺胞圧Palvを受ける区画は回路表で区別します。frespはHz、各振幅はmmHgです。操作画面のPEEPはcmH₂Oで、式には0.7355592401を掛けてmmHgへ換算します。baselineでは下式の全入力が0です。", "The node table distinguishes thoracic Pth from alveolar Palv exposure. fresp is Hz and amplitudes mmHg. Workbench PEEP is cmH₂O and is multiplied by 0.7355592401 for these mmHg equations. All respiratory inputs are zero at baseline.")],
    equations: [String.raw`M_\pm(a,b)=\frac{a+b\pm\sqrt{(a-b)^2+\epsilon^2}}2`, String.raw`\begin{aligned}P_{\mathrm{down,eff}}&=M_+(P_{\mathrm{down}},P_{\mathrm{ext}}+p_c),\\\chi&=\chi_{\mathrm{min}}+(1-\chi_{\mathrm{min}})\sigma\left(\frac{M_-(P_{\mathrm{up}}-P_{\mathrm{ext}},P_{\mathrm{down}}-P_{\mathrm{ext}})-p_c}{w}\right),\\Q&=\frac{P_{\mathrm{up}}-P_{\mathrm{down,eff}}}{R/\chi^2}.\end{aligned}`, String.raw`P_{\mathrm{th}}=P_{th,0}+0.20\,PEEP+A_{\mathrm{th}}\sin(2\pi f_{\mathrm{resp}}t),\quad P_{\mathrm{alv}}=PEEP+A_{\mathrm{alv}}\sin(2\pi f_{\mathrm{resp}}t)`],
  }],
  "coronary-coupling-v3": [{
    id: "coronary-storage", title: t("冠血管の容量と抵抗", "Coronary storage and resistance"),
    paragraphs: [t("各領域（LAD・LCx・RCA）は1つの大動脈側容量Artを持ち、そこから心外膜側・心内膜側の2経路へ分かれます。各経路は近位容量C1と遠位容量C2を持ち、共通冠静脈容量CVへ合流して右房へ戻ります。C1・C2という名称は区画名で、コンプライアンスそのものの数値ではありません。合計16容量を主循環と重複なくTBVへ含めます。", "Each territory has one large-arterial Art reservoir, splitting into epi/endo paths with proximal C1 and distal C2 storage, then merging into common venous CV and RA. C1/C2 name compartments, not numerical compliances. Sixteen coronary volumes contribute to TBV without duplication."),
      t("全冠区画に以下の圧–容量関係を使います。v＝V/Vref、m＝4、n＝2。CrefはV＝Vrefでの接線コンプライアンスです。虚脱による抵抗倍率fには別の基準容量Vhを使うため、Vrefと混同しないでください。a＝0.67、x＝min(1,max(0,V/Vh))とします。", "All coronary storage uses v=V/Vref, m=4, n=2; Cref is tangent compliance at Vref. Collapse resistance uses a different hydraulic reference Vh. With a=0.67, x=min(1,max(0,V/Vh)), compute f below."),
      t("各枝の流量は両端圧差／有効抵抗です。R1には自己調節トーンθとC1の虚脱倍率、Rmには両区画の虚脱倍率の幾何平均、R2にはC2の虚脱倍率を掛けます。構造的な抵抗倍率はbaselineで1、局所狭窄による追加損失は0です。", "Branch flow is pressure difference divided by effective resistance. R1 uses tone θ and C1 collapse; Rm the geometric mean of C1/C2 collapse; R2 C2 collapse. Structural multipliers are 1 and focal stenosis additions 0 at baseline.")],
    equations: [String.raw`p=P_*(v^m-v^{-n}),\quad P_*=\frac{V_{\mathrm{ref}}}{C_{\mathrm{ref}}(m+n)},\quad V>0`, String.raw`f(V)=\{a+(1-a)x^2(3-2x)\}^{-2}`, String.raw`R_{1,eff}=R_1\theta f(V_{C1}),\quad R_{\mathrm{m},eff}=R_m\sqrt{f(V_{C1})f(V_{C2})},\quad R_{2,eff}=R_2f(V_{C2})`],
  }, {
    id: "coronary-compression", title: t("心筋内圧と拍ごとの自己調節", "Intramyocardial pressure and beat-wise regulation"),
    paragraphs: [t("ArtとCVの外圧は共通心外圧Pe＝Pth＋Pperi、C1とC2の外圧は心筋内圧PIMです。壁重みwL・wS・wR、層深さd、短縮圧係数Kは表を参照します。中隔の深さsはLAD/LCxでd、RCAで1−dです。eMVC,wは直前の僧帽弁閉鎖時に更新する各壁の歪み。Fは弁の節で定義した正部分関数で幅0.005です。", "Art/CV external pressure is Pe=Pth+Pperi; C1/C2 use PIM. Weights wL/wS/wR, depth d and shortening gain K are tabulated. Septal depth s=d for LAD/LCx, 1−d for RCA. eMVC,w updates at the previous accepted mitral closure. F is the valve-section positive part with width 0.005."),
      t("短縮の基準更新には、受理されたステップでMV順行流が1 mL/s超から1 mL/s以下へ変わったときの歪みを使います。更新した基準は次のステップから使います。これは画像上の弁尖接合時刻や、指標計算で補間した弁閉鎖時刻と同じ定義ではありません。", "The shortening reference updates when accepted MV flow changes from >1 to ≤1 mL/s, using that endpoint's strains for subsequent steps. This is not an imaging leaflet-contact time or an interpolated metric closure time."),
      t("自己調節は各心周期を終えたときに更新し、その周期内ではトーンを保持します。Q̄mはRmを通る符号付き流量の周期平均、Qtargetは領域・層の安静目標です。ℓ＝ln θ、Tは周期長、τa＝25 s、θmin＝4/45、θmax＝2です。baselineでは需要倍率1・充血駆動0で、下式を使います。これは酸素需要から自律的に収縮力を変える機構ではありません。", "Tone is held within a cycle and updated at completion. Q̄m is signed cycle-mean flow through Rm; Qtarget is the resting target. ℓ=ln θ, T cycle length, τa=25 s, θmin=4/45 and θmax=2. Baseline demand=1 and hyperemia=0 give the update below. It does not autonomously alter contractility from oxygen demand.")],
    equations: [String.raw`P_{\mathrm{IM}}=P_e+(w_Ld+w_Ss)P_{\mathrm{tm},L}+[w_Rd+w_S(1-s)]P_{\mathrm{tm},R}+K\sum_w w_wF_{0.005}(1-e^{e_w-e_{\mathrm{MVC},w}})`, String.raw`\bar Q_{\mathrm{m},k}=\frac{1}{T}\sum_{n\text{ in cycle }k}\Delta t_n Q_{m,n+1}`, String.raw`\ell_{k+1}=\operatorname{clip}_{\ln\theta_{\mathrm{min}},\ln\theta_{\mathrm{max}}}\left[\ell_k+\frac{T}{\tau_a}\ln\max\left(\frac{\bar Q_{\mathrm{m},k}}{Q_{\mathrm{target}}},0.05\right)\right]`],
  }],
  "oxygen-balance-v1": [{
    id: "oxygen-equations", title: t("拍平均の酸素収支", "Beat-mean oxygen balance"),
    paragraphs: [t("酸素輸送は循環の解から計算する拍平均の代数評価で、血液量・張力へはフィードバックしません。Pは酸素分圧（mmHg）、Sは飽和度、Hbはg/dL、CはmL O₂/dLです。肺胞気と肺毛細管終末の酸素分圧を等しいと仮定します。PBは気圧、Rは呼吸交換比です。", "Oxygen transport is an algebraic beat-mean readout without feedback to blood volume or tension. P is O₂ pressure (mmHg), S saturation, Hb g/dL, C mL O₂/dL. Alveolar and end-capillary PO₂ are equated. PB is barometric pressure and R respiratory exchange ratio."),
      t("COはL/min、VO₂はmL/min、sは酸素混合上のシャント率です。sは循環回路に追加する血流接続ではありません。肺毛細管終末含量Cc、静脈含量Cv、動脈含量CaをFick収支と混合から求めます。CO≤0や負の必要含量なら評価不能とし、飽和度を見栄えのよい値に置換しません。", "CO is L/min, VO₂ mL/min and s an oxygen-mixing shunt fraction, not an added hydraulic connection. End-capillary Cc, venous Cv and arterial Ca satisfy Fick balance and content mixing. Nonpositive flow or negative required content makes the evaluation unavailable.")],
    equations: [String.raw`P_{\mathrm{AO}_2}=F_{\mathrm{IO}_2}(P_B-47)-P_{\mathrm{aCO}_2}/R>0,\quad S(P)=\frac{P^{2.7}}{26.8^{2.7}+P^{2.7}}`, String.raw`C(P)=1.34\,Hb\,S(P)+0.0031P,\quad D=\frac{VO_2}{10\mathrm{CO}},\quad C_a=C_c-\frac{s}{1-s}D,\quad C_v=C_a-D`],
  }],
};
