substitutions:
  _IMAGE: asia-northeast1-docker.pkg.dev/${PROJECT_ID}/circleheart/public-content:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.public-content
      - --tag
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}
